# Generated by Django 3.1.7 on 2021-05-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210507_1014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodjct',
            new_name='Product',
        ),
    ]
